# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
import numpy as np

print(np.__version__)

print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/envs/Johnny/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/Johnny/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/envs/Johnny/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/Johnny/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/envs/Johnny/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/Johnny/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/envs/Johnny/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/Johnny/include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
x = np.zeros(10)

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [32]:
from sys import getsizeof

n = np.zeros((10))

print(n,"\n")

print(n.size, "bytes") #size of the array
print(n.itemsize, "bytes") # memory size of one array element
print(n.size*n.itemsize, "bytes") # memory size of an array
print(n.nbytes,"bytes") # memory size of an array




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

10 bytes
8 bytes
80 bytes
80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [38]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [37]:
x = np.zeros(10)
x[4]= 1
print(x)

array = np.eye( 10 )[ 5 - 1 ]
print (array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [49]:
array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [55]:
array = array [::-1]
print(array[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [57]:
x = np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [67]:
arr = np.array([1,2,0,0,4,0])

np.nonzero(arr)

print (np.nonzero(arr))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [69]:
array = np.identity(3)

print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [77]:
array_3x3x3 = np.random.random((3,3,3))

print(array_3x3x3)

[[[0.83844534 0.18680057 0.54622017]
  [0.65466226 0.54224146 0.99288744]
  [0.73950319 0.74185262 0.38440371]]

 [[0.71935766 0.74556491 0.05021711]
  [0.85181831 0.07467059 0.94577812]
  [0.7882733  0.08333767 0.84555381]]

 [[0.40788098 0.54690951 0.5476723 ]
  [0.84068738 0.74029336 0.93089983]
  [0.68737012 0.99422527 0.85792087]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [92]:
x = np.random.random((10,10))

print(x, "\n")

xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:","\n")
print(xmin.round(8), xmax.round(8))

[[7.55707830e-01 8.29479941e-01 7.87503195e-01 4.12244414e-01
  1.25053585e-01 8.24270535e-01 1.28139081e-01 6.27169696e-01
  6.44069028e-01 9.28254609e-01]
 [1.30116487e-01 1.03160733e-01 9.29763654e-01 7.96200450e-01
  7.26021001e-01 9.91830411e-01 9.37375310e-01 9.36469004e-01
  8.25072585e-01 1.04899803e-01]
 [6.03199222e-01 6.78032850e-01 1.51642361e-01 7.38662956e-01
  4.53366988e-01 3.37330146e-01 1.25732092e-01 3.82894297e-01
  9.59877671e-01 5.27060907e-01]
 [7.23228148e-01 8.83616293e-01 1.87755154e-01 8.12397412e-01
  1.55764727e-03 1.96756410e-01 1.69135539e-01 1.35099818e-01
  4.09082161e-01 6.98305979e-01]
 [4.90322062e-01 2.68600337e-01 6.56924437e-01 5.53770953e-01
  6.21640180e-02 6.70147112e-02 9.49937058e-02 5.18011983e-01
  9.50790974e-02 9.66076907e-01]
 [3.84842667e-02 7.08149095e-01 6.04785806e-02 7.17831385e-01
  4.67005873e-01 6.78134994e-01 1.44062629e-01 7.19814239e-01
  3.24895440e-01 7.11601550e-01]
 [3.31872239e-01 8.18838783e-01 9.17465913e-02 7.98526675e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [103]:
x = np.random.random((3,10))

print(x, "\n")

print(np.mean(x).round(8))

[[0.8436609  0.74590404 0.6707048  0.3160923  0.17272072 0.02925657
  0.00291866 0.78097761 0.36954623 0.88545115]
 [0.36768842 0.29327775 0.91638269 0.29726517 0.51765099 0.04716862
  0.38145229 0.48122966 0.40353946 0.42897847]
 [0.94306391 0.59832137 0.40832279 0.89737506 0.81541228 0.60134905
  0.96178318 0.62179468 0.98714407 0.92942064]] 

0.55719512


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [173]:
x = np.ones((4,4))

print("Original array:","\n")

print(x,"\n")

print("1 on the border and 0 inside in the array","\n")

x[1:-1,1:-1] = 0

print(x)

Original array: 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

1 on the border and 0 inside in the array 

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [120]:
x = np.ones((3,3))

print("Original array:")
print(x, "\n")

print("0 on the border and 1 inside in the array")

x = np.pad(x, pad_width = 1, mode = 'constant', constant_values = 0)

print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [123]:
True

True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [136]:
x = np.diag([1, 2, 3, 4, 5])

print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [146]:
x = np.ones((3,3))

print("Checkerboard pattern:", "\n")

x = np.zeros((8,8),dtype=int)

x[1::2,::2] = 1
x[::2,1::2] = 1




Checkerboard pattern: 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [147]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [160]:
array = np.array([[0,1], [1,0]])

x = np.tile(array,(4,4))

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [161]:
Z = np.random.random((5,5))

Zmax, Zmin = Z.max(), Z.min()

Z = (Z-Zmin) / (Zmax-Zmin)

print (Z)

[[0.4701145  1.         0.81206806 0.         0.96720689]
 [0.80859404 0.07511827 0.62264757 0.87333778 0.70651989]
 [0.43509163 0.02293152 0.15419354 0.24746275 0.09019103]
 [0.72756384 0.77272485 0.42933394 0.90999844 0.47487738]
 [0.155482   0.26923292 0.29617602 0.16322248 0.6160929 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [164]:
color = np.dtype([("r", np.ubyte, 1), # dtype structured data type
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-164-aeefdaf704c1>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1), # dtype structured data type


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [174]:
real_matrix_product = np.dot(np.ones((5,3)), np.ones((3,2)))

print (real_matrix_product)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [175]:
Z = np.arange(11)

Z[(3 < Z) & (Z < 8)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [176]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [180]:
print (np.array(0) / np.array(0))
print (np.array(0) // np.array(0))
print (np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-180-6d7d12044e63>:1: RuntimeWarning: invalid value encountered in true_divide
  print (np.array(0) / np.array(0))
<ipython-input-180-6d7d12044e63>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print (np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [185]:
import numpy as np

a = np.array([0.015, 0.235, 0.112])

np.round(a, 1)

array([0. , 0.2, 0.1])

#### 30. How to find common values between two arrays? (★☆☆)

In [187]:
array1 = np.array([0, 10, 20, 40, 60])

print("Array1: ",array1)

array2 = [10, 30, 40]

print("Array2: ",array2,"\n")

print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40] 

Common values between two arrays:
[10 40]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [188]:
warnings.filterwarnings('ignore')


NameError: name 'warnings' is not defined

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [192]:
np.sqrt(-1) == np.emath.sqrt(-1)


<ipython-input-192-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [196]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

print("Yesterday: ",yesterday)

today     = np.datetime64('today', 'D')

print("Today: ",today)

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Tomorrow: ",tomorrow)

Yesterday:  2020-12-06
Today:  2020-12-07
Tomorrow:  2020-12-08


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [206]:
x = np.zeros((5,5))

print("Original array:","\n")
print(x,"\n")
print("Row values ranging from 0 to 4.","\n")

x += np.arange(5)

print(x)

Original array: 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

Row values ranging from 0 to 4. 

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [203]:
def generate():
   for n in range(10):
       yield n
        
nums = np.fromiter(generate(),dtype = float,count =- 1)

print(nums)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [215]:
x = np.linspace(0,1,12,endpoint = True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [199]:
x = np.random.random(10)

print("Original array:","\n")

print(x,"\n")

x.sort()

print("Sorted array:","\n")

print(x)

Original array: 

[0.76105173 0.58728914 0.68501032 0.08645407 0.73652621 0.02213613
 0.76464288 0.4691456  0.70135209 0.01005248] 

Sorted array: 

[0.01005248 0.02213613 0.08645407 0.4691456  0.58728914 0.68501032
 0.70135209 0.73652621 0.76105173 0.76464288]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [218]:
x = np.random.randint(0,2,6)
print("First array:")
print(x,"\n")

y = np.random.randint(0,2,6)
print("Second array:")
print(y,"\n")

print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 0 1 0 1] 

Second array:
[1 1 0 0 1 0] 

Test above two arrays are equal or not!
False


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [201]:
nums = np.arange(2000)
np.set_printoptions(threshold=sys.maxsize)
print(nums)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)